kafka:
  servers:
  - "kafka-f7ae38e-vladanovic-4654.aivencloud.com:23702"
  topic: "sitestats"
  cafile: "./certs/ca.pem"
  cert: "./certs/service.cert"
  key: "./certs/service.key"
  passwd: ""
postgres:
  dbhost: "pg-2e0f365c-vladanovic-4654.aivencloud.com"
  dbport: 23700
  dbname: "defaultdb"
  dbuser: "avnadmin"
  dbpass: ""
  dbcert: "./certs/pg.pem"
  batch_size: 10
sites:
- url: "https://example.com"
  regex: "domain"
  check_interval: 17
- url: "https://github.com/status"
  regex: "^Github lives!.*"
  check_interval: 31
- url: "https://medium.com/status"
  check_interval: 11
- url: "https://help.netflix.com/en/is-netflix-down"
  regex: "Netflix is up"
  check_interval: 37
- url: "https://status.aiven.io/"
  regex: "All Systems Operational"
  check_interval: 43
logging:
  version: 1
  formatters:
    standard:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    error:
      format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: standard
      stream: ext://sys.stdout
  root:
    level: DEBUG
    handlers: [console]
    propogate: yes
